### ISSUE TITLE
Vim runtime not propagated correctly

### ISSUE THREAD

**Issue by elGatoMantocko** [mkaczanowski/pkgbuilds#1]
I had never had a problem with vim runtime, but recently I decided to use this package instead of building directly from source. I noticed that the runtime directory doesn't get copied over to the proper place and was wondering if that is something that should be handled by this project.

To be exact, my vimrc has dependencies that needed to be found in /usr/share/vim/vim74 but this doesn't build there. Is that something that I should just change in the make command of the PKGBUILD file, or should there be a setting pushed up?

**Comment by mkaczanowski** [comment]
hey @elGatoMantocko the `vim-runtime` is actually a separate package.

This diff should fix it for you:
https://github.com/mkaczanowski/pkgbuilds/commit/73f624a1195655acd798fc50b41d1cd456beb5b2
